universe = container
container_image = containers/simrobot.sif

out = data/output/$(run_name).out
log = data/logs/$(run_name).log
error = data/error/$(run_name).err

arguments=$(params)

executable = exe/run_image.sh

transfer_input_files = data/simrobot.def
transfer_output_files = tempdata.txt
transfer_output_remaps = "tempdata.txt = data/results/$(run_name)_$(Process).txt"

requirements = (HasCHTCStaging == true)

request_cpus = 8
request_memory = 16GB
request_disk = 50GB

queue params from $(commands_file)